theme: jekyll-theme-cayman
title: Eric's Projects
description: A site to share my current projects.

navbar-links:
  About Me: ""
  Resources:
    - Beautiful Jekyll: ""
    - Learn markdown: ""
    - GitHub Pages: ""
  Author's home: ""
  
  share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true
  
  plugins:
  - jekyll-paginate
  - jekyll-sitemap

